-- Data Exploration Queries  
-- we have five tables so we are going to see them
-- NOTE : All these questions are the created by me according to my needs to understand data 
use telecome_pro

-- Question No 1
-- what  are the total sales before the launch of 5g
-- ANS = 882.36

select  sum(plan_revenue_crores) from fact_plan_revenue
inner join dim_date on
fact_plan_revenue.date = dim_date.date 
where beforeAfter_5g="Before 5G"

-- Question No # 2
-- what  are the total sales AFTER  the launch of 5g
-- ANS = 1068.38
select  sum(plan_revenue_crores) from fact_plan_revenue
inner join dim_date on
fact_plan_revenue.date = dim_date.date 
where beforeAfter_5g="after 5g"

-- QUESTION 3
-- WHAT ARE THE TOP 5 PLANS CUSTOMER BOUGHT 
--ANS -- P1,2,3,4,11

SELECT PLANS , SUM(PLAN_REVENUE_CRORES ) AS PL_REV FROM FACT_PLAN_REVENUE 
GROUP BY PLANS
ORDER BY PL_REV DESC 
LIMIT 5 ;

-- QUESTION 4
-- WHAT ARE THE TOP 5 PLANS CUSTOMER BOUGHT BEFORE 5G 
-- ANS P1,2,3,4,5

SELECT PLANS , SUM(PLAN_REVENUE_CRORES ) AS PL_REV FROM FACT_PLAN_REVENUE INNER JOIN 
DIM_DATE ON FACT_PLAN_REVENUE.DATE = DIM_DATE.DATE
WHERE BeforeAfter_5g = "BEFORE 5G"   
GROUP BY PLANS
ORDER BY PL_REV DESC 
LIMIT 5 ;

-- QUESTION 5
-- WHAT ARE THE TOP 5 PLANS CUSTOMER BOUGHT AFTER 5G 
-- ANS P1,11,2,3,12

SELECT PLANS , SUM(PLAN_REVENUE_CRORES ) AS PL_REV FROM FACT_PLAN_REVENUE INNER JOIN 
DIM_DATE ON FACT_PLAN_REVENUE.DATE = DIM_DATE.DATE
WHERE BeforeAfter_5g = "AFTER 5G"   
GROUP BY PLANS
ORDER BY PL_REV DESC 
LIMIT 5 ;

-- QUESTION NO 6 
-- H0W MUCH ACTOVE USERS BEFORE 5G LAUNCH
-- ANS  843 LAKHS

SELECT BEFOREAFTER_5G ,SUM( ACTIVE_USERS_LAKHS ) AS SUM_USERS FROM FACT_ATLIQO_METRICS 
INNER JOIN DIM_DATE ON
FACT_ATLIQO_METRICS.DATE = DIM_DATE.DATE
WHERE BEFOREAFTER_5G = "BEFORE 5G" ;

-- QUESTION NO 6 
-- H0W MUCH ACTOVE USERS AFTER 5G LAUNCH
-- ANS  773 LAKHS

SELECT BEFOREAFTER_5G ,SUM( ACTIVE_USERS_LAKHS ) AS SUM_USERS FROM FACT_ATLIQO_METRICS 
INNER JOIN DIM_DATE ON
FACT_ATLIQO_METRICS.DATE = DIM_DATE.DATE
WHERE BEFOREAFTER_5G = "AFTER 5G" ;

-- QUESTION NO 7
-- H0W MUCH  USERS UNSUBSCRIBE SERVICE BEFORE THE LAUNCH OF 5G 
-- ANS 56.33 LAKHS

SELECT BEFOREAFTER_5G ,SUM(UNSUBSCRIBED_USERS_LAKHS) AS SUM_UNSB FROM FACT_ATLIQO_METRICS 
INNER JOIN DIM_DATE ON
FACT_ATLIQO_METRICS.DATE = DIM_DATE.DATE
WHERE BEFOREAFTER_5G = "BEFORE 5G" ;

-- QUESTION NO 7
-- H0W MUCH  USERS UNSUBSCRIBE SERVICE BEFORE THE LAUNCH OF 5G 
-- ANS 69.57 LAKHS

SELECT BEFOREAFTER_5G ,SUM(UNSUBSCRIBED_USERS_LAKHS) AS SUM_UNSB FROM FACT_ATLIQO_METRICS 
INNER JOIN DIM_DATE ON
FACT_ATLIQO_METRICS.DATE = DIM_DATE.DATE
WHERE BEFOREAFTER_5G = "AFTER 5G" ;

-- QUESTION NO 8
-- WHAT IS THE MIN(AVG_REV) & MAX(AVG_REV) & OVERALL AVERAGE REVENUE PER USER BEFORE 5G WAS LAUNCHED
-- ANS 	BEFOREAFTER_5G	MIN(ARPU)	MAX(ARPU)	AVG(ARPU)
--             Before 5G	162	213	190.2333

SELECT BEFOREAFTER_5G, MIN(ARPU), MAX(ARPU), AVG(ARPU) FROM FACT_ATLIQO_METRICS
INNER JOIN DIM_DATE ON
FACT_ATLIQO_METRICS.DATE = DIM_DATE.DATE 
WHERE  BEFOREAFTER_5G ="BEFORE 5G" AND COMPANY = "ATLIQO"

-- QUESTION NO 9
-- WHAT IS THE MIN(AVG_REV) & MAX(AVG_REV) & OVERALL AVERAGE REVENUE PER USER AFTER 5G WAS LAUNCHED
-- ANS 		BEFOREAFTER_5G	MIN(ARPU)	MAX(ARPU)	AVG(ARPU)
--	                After 5G	161	255	211.2500
-- SERVICES CHARGES GET HIGH AFTER THE LAUNCH OF 5G

SELECT BEFOREAFTER_5G, MIN(ARPU), MAX(ARPU), AVG(ARPU) FROM FACT_ATLIQO_METRICS
INNER JOIN DIM_DATE ON
FACT_ATLIQO_METRICS.DATE = DIM_DATE.DATE 
WHERE  BEFOREAFTER_5G ="AFTER 5G" AND COMPANY = "ATLIQO"

-- QUESTION NO : 10
-- I NEED TO CHECK THE TOTAL ACTIVE USERS PER MONTH

SELECT DISTINCT(MONTH_NAME), SUM(ACTIVE_USERS_LAKHS) OVER (PARTITION BY MONTH_NAME) ACTIVE_USERS FROM DIM_DATE
INNER JOIN FACT_ATLIQO_METRICS ON
DIM_DATE.DATE = FACT_ATLIQO_METRICS.DATE
ORDER BY ACTIVE_USERS

-- QUESTION  NO : 11
-- ACTIVE USER PER MONTH BEFORE 5G
-- ANS Jan	191.71000000000004 / Apr	210.95999999999998 / Mar	212.57999999999996 / Feb	228.28000000000006

SELECT DISTINCT(MONTH_NAME), SUM(ACTIVE_USERS_LAKHS) OVER (PARTITION BY MONTH_NAME) ACTIVE_USERS FROM DIM_DATE
INNER JOIN FACT_ATLIQO_METRICS ON
DIM_DATE.DATE = FACT_ATLIQO_METRICS.DATE
WHERE BEFOREAFTER_5G ="BEFORE 5G"
ORDER BY ACTIVE_USERS

-- QUESTION  NO : 12
-- ACTIVE USER PER MONTH AFTER 5G
-- ANS Jun	169.94 / Sep	188.22000000000003 / Aug	204.41 /Jul	211.13

SELECT DISTINCT(MONTH_NAME), SUM(ACTIVE_USERS_LAKHS) OVER (PARTITION BY MONTH_NAME) ACTIVE_USERS FROM DIM_DATE
INNER JOIN FACT_ATLIQO_METRICS ON
DIM_DATE.DATE = FACT_ATLIQO_METRICS.DATE
WHERE BEFOREAFTER_5G ="AFTER 5G"
ORDER BY ACTIVE_USERS

-- QUESITON NO ; 13
-- FIND THE TOP 2 CITIES WITH HIGHEST COMPANY MARKET VALUE  , BEFORE 5G 

SELECT FACT_MARKET_SHARE.COMPANY, SUM(TMV_CITY_CRORES)
OVER (PARTITION BY FACT_MARKET_SHARE.COMPANY ) AS TMV FROM FACT_MARKET_SHARE
INNER JOIN FACT_ATLIQO_METRICS ON
FACT_MARKET_SHARE.CITY_CODE = FACT_ATLIQO_METRICS.CITY_CODE
ORDER BY TMV DESC

-- QUESTION NO 14 
-- HOW MUCH PERCENT MARKET SHARE ALL THE COMPANIES HOLD IN THESE MONTHS
-- WANT TO CHECK TOP COMPANY

SELECT MONTH_NAME ,COMPANY, AVG(MS_PCT) AS AVG_MS FROM FACT_MARKET_SHARE 
INNER JOIN DIM_DATE ON FACT_MARKET_SHARE.DATE = DIM_DATE.DATE 
GROUP BY MONTH_NAME , COMPANY
ORDER BY AVG_MS DESC
LIMIT 5 ;

-- MARKET_SHARE OF ALL COMPANIES

SELECT CITY_CODE, SUM(TMV_CITY_CRORES), RANK() OVER (ORDER BY SUM(TMV_CITY_CRORES)) AS ranking
FROM FACT_MARKET_SHARE
GROUP BY CITY_CODE;



